# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  # config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before do
    Kernel.stub(:spawn).and_raise("Spawning is not permitted in specs.  Please change your spec to use expectations/stubs.")
  end

  config.after do
    clear_caches
  end
end

begin
  require 'coveralls'
  Coveralls.wear!
rescue LoadError
end

require 'linux_admin'


def data_file_path(to)
  File.expand_path(to, File.join(File.dirname(__FILE__), "data"))
end

def sample_output(to)
  File.read(data_file_path(to))
end

def clear_caches
  LinuxAdmin::RegistrationSystem.instance_variable_set(:@registration_type, nil)
end

class LinuxAdmin
  module Distros
    # simply alias test distro to redhat distro for time being
    Distros::Test = Distros::RedHat
  end
end
